-- 크로스체크 오탐 케이스 저장 (2026-03-01)
-- 10개 병원 크로스체크에서 발견된 오탐 패턴

INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_001', 'crosscheck_20260301', 'P-56-11-001', '인증', '개인정보처리방침의 회원인증 관련 문구', 'always_safe', 'system', '개인정보처리방침/법적문서 내 용어 - 위반 아님', 'confirmed', 'add_exception', '규칙엔진 네거티브 리스트 추가', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_002', 'crosscheck_20260301', 'P-56-11-001', '승인', '카드결제 승인 정보 보존', 'always_safe', 'system', '개인정보처리방침 내 카드결제 관련 용어 - 위반 아님', 'confirmed', 'add_exception', '규칙엔진 네거티브 리스트 추가', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_003', 'crosscheck_20260301', 'P-56-13-001', '처방전', '전자처방전을 약국으로 보내기', 'always_safe', 'system', '병원 서비스 안내 처방전 발급 기능 - 위반 아님', 'confirmed', 'add_exception', '규칙엔진 네거티브 리스트 추가', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_004', 'crosscheck_20260301', 'P-56-32-001', '기적', '정기적 직원 교육 등', 'partial_match', 'system', '정기적의 부분문자열 매칭 오탐', 'confirmed', 'modify_pattern', '정규식에 단어 경계 추가', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_005', 'crosscheck_20260301', 'P-56-42-003', '건강보험', '건강보험증 QR출입증', 'always_safe', 'system', '병원 서비스 안내 메뉴 - 위반 아님', 'confirmed', 'add_exception', '규칙엔진 네거티브 리스트 추가', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_006', 'crosscheck_20260301', 'P-56-32-006', '명의', '[EBS] [명의] 허리 수술', 'context_dependent', 'system', 'TV 프로그램 제목 인용 - 위반 아님', 'confirmed', 'add_exception', '맥락 예외 추가 - 방송/프로그램 제목', datetime('now'));
INSERT OR IGNORE INTO false_positive_cases (id, analysis_id, pattern_id, matched_text, full_context, fp_type, reporter_type, report_reason, status, resolution, resolution_note, created_at) VALUES ('fp_xcheck_007', 'crosscheck_20260301', 'P-56-09-001', '비용 청구', '국민건강보험법에 의해 요양급여비용 청구', 'always_safe', 'system', '개인정보처리방침 내 법적 의무사항 - 위반 아님', 'confirmed', 'add_exception', '법적 문서 맥락 예외 추가', datetime('now'));
